# The URL the site will be built for
base_url = "https://felixhenninger.github.io/tapp/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Theme
theme = "soda-base"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
site_title = "Transatlantic Privacy Perceptions"
site_logo = "assets/logo_full.svg"
site_logo_1 = "assets/tapp_logo_white_1.svg"
site_logo_2 = "assets/tapp_logo_white_2.svg"
site_logo_3 = "assets/tapp_logo_white_3.svg"
site_logo_footer = "assets/mark_white.svg"
site_logo_alt = "TAPP panel logo"
site_logo_sr = "TAPP panel logo"
site_tagline = ""
copyright = "2024&ndash; Transatlantic Privacy Perceptions. All rights reserved."
# Additional call to action in site navigation
#header_cta = "Contact"
#header_cta_href = "contact"


hero_image="assets/hero.png"