[[person]]
name = "Brian Kim"
role = "Principal investigator"
institution = "University of Maryland"
image = "photos/Brian.jpg"

[[person]]
name = "Frauke Kreuter"
role = "Principal investigator"
institution = "University of Maryland & LMU Munich"
image = "photos/Frauke.jpg"

[[person]]
name = "Christoph Kern"
role = "Principal investigator"
institution = "LMU MUNICH"
image = "photos/kern.jpg"

[[person]]
name = "Jessica Vitak"
role = "Principal investigator"
institution = "University of Maryland"
image = "photos/Jessica.jpg"

[[person]]
name = "Stanley Presser"
role = "Principal investigator"
institution = "University of Maryland"
image = "photos/Stanley.jpg"

[[person]]
name = "Katie Shilton"
role = "Principal investigator"
institution = "University of Maryland"
image = "photos/Katie.jpg"

[[person]]
name = "Wiebke Weber"
role = "Team"
institution = "LMU MUNICH"
image = "photos/Wiebke.jpg"

[[person]]
name = "Sonja Kellner"
role = "Team"
institution = "LMU Munich & Microsoft"
image = "photos/Sonja.jpeg"

[[person]]
name = "Mariel McKone Leonard"
role = "Team"
institution = ""
image = "photos/Mariel.jpg"

[[person]]
name = "Srija Mukhopadhyay"
role = "Team"
institution = "LMU Munich"
image = "photos/Srija.jpg"

[[person]]
name = "Trent Buskirk"
role = "Team"
institution = "Bowling Green State University"
image = "photos/Trent.jpg"

[[person]]
name = "Thomas Fetzer"
role = "Team"
institution = "University of Mannheim"
image = "photos/Thomas.jpg"

[[person]]
name = "Olga Kononykhina"
role = "Team"
institution = "LMU Munich"
image = "photos/Olga.jpg" 

[[person]]
name = "Aida Kreider"
role = "Team"
institution = "LMU Munich"
image = "photos/Aida.jpg"

[[person]]
name = "Anna Fuchs"
role = "Team"
institution = "LMU Munich"
image = "photos/Anna.jpg"
