[[news]]
title="this is a title"
anews="""â°Data collection for the Transatlantic Privacy Perceptions survey is halfway through. 
As a privacy expert, your insights into the #AI tools and frameworks your organization/company is currently using, as well as the #governance and #privacy structures in place, are invaluable. Your participation will provide essential data that helps shape the dialogue on AI governance and privacy on both sides of the Atlantic. 

Please, do not delay your participation. Your contribution is vital, and together, we will make a significant impact.

â±The survey will only take 2-5 minutes of your time. 

Join here: [https://lnkd.in/drDkthgp](https://lnkd.in/drDkthgp)

ğŸ“TAPP is a research project conducted at the Universities of Maryland (UMD) ğŸ‡ºğŸ‡¸ and Munich (LMU) ğŸ‡©ğŸ‡ª.

ğŸ“…The results will be published in June (we are all about speedy science ğŸ˜ ). You can find our previous results here. [https://lnkd.in/d3aN7i6w](https://lnkd.in/d3aN7i6w)"""
date="2021-70-03"
pin="true"
skip_feed="true"


[[news]]
anews="""â°Let's talk about Privacy 101 Part 2.

Earlier, I discussed what control over your own data means for users and companies, why it is important for AI, and how you can have more control over the data you share with AI algorithms. You can find the post here: https://lnkd.in/deu48y_6

Today, let's focus on privacy by design. According to our study, Transatlantic Privacy Perceptions (TAPP), 48% of our experts believe that privacy by design should be one of the guiding principles for developing AI frameworks and guidelines.

ğŸ¤”What does privacy by design actually mean? It refers to integrating privacy into the design process from the very beginning, such as setting the highest privacy options as the default.

 âœ Why is privacy by design important for AI? We share a lot of information either directly with chatbots or through the data that companies have about our behavior, preferences, purchases, and so on, which is then used to train AI models and develop more advanced chatbots. 

â˜‘ For users, privacy by design reduces the mental load when using apps.
â˜‘ Privacy by design significantly reduces the amount of user input data that a company can use for training AI or selling to another company to train their AI.
â˜‘ It potentially reduces data leaks (if nothing is collected in the first place)
â˜‘ While many companies discuss corporate digital responsibility ğŸ“£ , privacy by design would be an important and impactful practice in this area. 

ğŸš€ What does privacy by design look like? For example, if ChatGPT had a "temporary chat" option set as the default and users had to opt in to share their chat history for future training, that would be an example of privacy by design.

If you want to learn more about the work we do at the Transatlantic Privacy Survey project, please visit: https://lnkd.in/dVctmQRp"""

date="2021-70-03"
originalurl="https://www.linkedin.com/posts/tapp-insights_activity-7221104622008995840-4O9c"
by="Olga Kononykhina"
pin="true"

[[news]]
anews="""â°Data collection for the Transatlantic Privacy Perceptions survey is halfway through. 
As a privacy expert, your insights into the #AI tools and frameworks your organization/company is currently using, as well as the #governance and #privacy structures in place, are invaluable. Your participation will provide essential data that helps shape the dialogue on AI governance and privacy on both sides of the Atlantic. 

Please, do not delay your participation. Your contribution is vital, and together, we will make a significant impact.

â±The survey will only take 2-5 minutes of your time. 

Join here: [https://lnkd.in/drDkthgp](https://lnkd.in/drDkthgp)

ğŸ“TAPP is a research project conducted at the Universities of Maryland (UMD) ğŸ‡ºğŸ‡¸ and Munich (LMU) ğŸ‡©ğŸ‡ª.

ğŸ“…The results will be published in June (we are all about speedy science ğŸ˜ ). You can find our previous results here. [https://lnkd.in/d3aN7i6w][https://lnkd.in/d3aN7i6w]"""
date="2021-70-03"
pin="true"


[[news]]
anews="""â°Data collection for the Transatlantic Privacy Perceptions survey is halfway through. 
As a privacy expert, your insights into the #AI tools and frameworks your organization/company is currently using, as well as the #governance and #privacy structures in place, are invaluable. Your participation will provide essential data that helps shape the dialogue on AI governance and privacy on both sides of the Atlantic. 

Please, do not delay your participation. Your contribution is vital, and together, we will make a significant impact.

â±The survey will only take 2-5 minutes of your time. 

Join here: [https://lnkd.in/drDkthgp](https://lnkd.in/drDkthgp)

ğŸ“TAPP is a research project conducted at the Universities of Maryland (UMD) ğŸ‡ºğŸ‡¸ and Munich (LMU) ğŸ‡©ğŸ‡ª.

ğŸ“…The results will be published in June (we are all about speedy science ğŸ˜ ). You can find our previous results here. [https://lnkd.in/d3aN7i6w][https://lnkd.in/d3aN7i6w]"""
date="2021-70-03"
pin="true"