[[accordion]]
visible = "Why did you ask me to be part of the panel?"
hidden = "We, or someone who knows you professionally, thought that you would provide a unique voice in the TAPP panel!"

[[accordion]]
visible = "What will be done with my responses?"
hidden = """Data collected through the TAPP panel survey is protected in line with <a href="https://www.qualtrics.com/privacy-statement/">EU GDPR</a> and by the UMD research ethics committee (IRB). In line with the open science movement, we will make selected survey data available for research purposes. No identifying information will be contained in this dataset.

Data published in reports are aggregated and will not individually identify you or your responses.

In line with the open science movement, we will make selected survey data available for research purposes. No identifying information will be contained in this dataset."""

[[accordion]]
visible = "What can I do to be more involved in this project?"
hidden = """Use our data. Submit a question or topic to ask our respondents."""

[[accordion]]
visible = "Who should I contact with questions about this project?"
hidden = """To learn more about TAPP panel participation, please refer to the FAQs or <a href="mailto:irb@umd.edu">email</a>.
If you have questions about your rights as a research participant or wish to report a research-related injury, please contact with reference to IRB No. 1934146-4:

University of Maryland College Park
Institutional Review Board Office
1204 Marie Mount Hall
College Park, Maryland, 20742
E-mail: <a href="mailto:irb@umd.edu">irb@umd.edu</a>
Telephone: +1 301-405-0678

For more information regarding your rights as a research participant, please visit the <a href="https://research.umd.edu/research-resources/research-compliance/institutional-review-board-irb/research-participants">UMD IRB FAQs</a>."""

[[accordion]]
visible = "Who is funding this research?"
hidden = """TAPP is supported by research grants from Meta, the U.S. Census Bureau, and the Volkswagen Foundation. Research is being conducted entirely independently of any funding sources."""

[[accordion]]
visible = "What is a panelist?"
hidden = """A panelist is anyone who participates in our survey and agrees to be contacted additionally throughout the year to participate in further waves."""

[[accordion]]
visible = "Who can answer the questionnaire?"
hidden = """Anyone aged 18+ living or working in countries/regions on either side of the Atlantic Ocean who is passionate and knowledgeable about digital privacy is invited to join the panel."""

[[accordion]]
visible = "Can I suggest a question for the next questionnaire?"
hidden = """Of course, send us an email at <a href="mailto:info@privacyperceptions.org">info@privacyperceptions.org</a>"""

[[accordion]]
visible = "How can I use the data?"
hidden = """We're currently transferring the anonymized data from our study to GESIS (Leibniz Institute for the Social Sciences), a German institute that handles social science data. The link to the archived data will be shared here once that's done."""

[[accordion]]
visible = "How many questions are in the questionnaire?"
hidden = """The number of questions varies by survey wave and questionnaire topic. Regardless of the topic, we keep the questionnaires short, so that participating takes no more than 5-10 minutes of your time."""

[[accordion]]
visible = "How can I participate?"
hidden = """Send us an email at <a href="mailto:info@privacyperceptions.org">info@privacyperceptions.org</a>"""

[[accordion]]
visible = "I’ve received a TAPP invitation. Now what?"
hidden = '''Our panel is unique in regularly bringing together the opinions of a diverse set of privacy experts from a variety of industries and countries. Participating gives you the opportunity to raise awareness about the privacy issues you care about and contribute to <a href="@/results/index.md"><svg width="20" height="20" style="display: inline-block; vertical-align: middle; margin-right: 5px;" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13.0627 16.6355L11.1259 14.6987L15.9093 9.91526L11.0838 5.08986L13.0367 3.13696L19.799 9.89922L13.0627 16.6355Z" fill="#071A2D"/><path d="M17.8282 8.45024L1.37982 8.51807L1.36848 11.2685L17.8168 11.2007L17.8282 8.45024Z" fill="#071A2D"/></svg>scientific research</a>. To get started, simply click 'Start survey' in your invitation email!'''

[[accordion]]
visible = "What is TAPP’s privacy and data protection policy?"
hidden = '''We take privacy and <a href="@/data_protection/index.md"><svg width="20" height="20" style="display: inline-block; vertical-align: middle; margin-right: 5px;" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13.0627 16.6355L11.1259 14.6987L15.9093 9.91526L11.0838 5.08986L13.0367 3.13696L19.799 9.89922L13.0627 16.6355Z" fill="#071A2D"/><path d="M17.8282 8.45024L1.37982 8.51807L1.36848 11.2685L17.8168 11.2007L17.8282 8.45024Z" fill="#071A2D"/></svg>data protection</a> seriously. Below is our data protection statement. This statement is also available from within the current TAPP panel survey.'''

[[accordion]]
visible = "I don’t want to participate anymore. How can I leave the panel?"
hidden = """We’re sorry to see you go! Contact us at <a href="mailto:info@privacyperceptions.org">info@privacyperceptions.org</a> to request removal from our invitation list. Please be aware that as all data is collected anonymously, we are not able to remove your individual data from previous datasets."""
